import { theme as antdTheme } from 'antd'

const { defaultAlgorithm } = antdTheme

const tokens = {
  fontFamily: "'Geist Variable', 'Geist Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  fontFamilyCode: "'Geist Mono', 'JetBrains Mono', 'SFMono-Regular', monospace",
  borderRadius: 12,
  borderRadiusLG: 16,
  borderRadiusSM: 8,
  borderRadiusXS: 6,
  colorPrimary: '#2F6BFF',
  colorInfo: '#2F6BFF',
  colorSuccess: '#16A34A',
  colorWarning: '#D97706',
  colorError: '#DC2626',
  colorLink: '#2F6BFF',
  colorLinkHover: '#2459E5',
  colorBgBase: '#F5F7FB',
  colorBgLayout: '#F5F7FB',
  colorBgContainer: '#FFFFFF',
  colorBgElevated: '#FFFFFF',
  colorFillAlter: '#F8FAFC',
  colorFillSecondary: '#F1F5F9',
  colorBorder: '#E4E7EC',
  colorBorderSecondary: '#EEF2F6',
  colorText: '#0F172A',
  colorTextSecondary: '#475467',
  colorTextDescription: '#667085',
  colorTextTertiary: '#98A2B3',
  colorPrimaryBg: 'rgba(47, 107, 255, 0.12)',
  colorPrimaryBgHover: 'rgba(47, 107, 255, 0.18)',
  colorPrimaryBorder: 'rgba(47, 107, 255, 0.3)',
  colorPrimaryBorderHover: 'rgba(47, 107, 255, 0.44)',
  colorPrimaryHover: '#2459E5',
  colorPrimaryActive: '#1E4FD1',
  controlHeight: 40,
  controlHeightLG: 44,
  controlHeightSM: 32,
  controlOutline: 'rgba(47, 107, 255, 0.18)',
  controlOutlineWidth: 3,
  fontSize: 14,
  fontSizeLG: 16,
  fontSizeXL: 18,
  fontSizeHeading1: 40,
  fontSizeHeading2: 28,
  fontSizeHeading3: 22,
  fontSizeHeading4: 18,
  fontWeightStrong: 600,
  lineHeight: 1.5,
  motionDurationFast: '0.16s',
  motionDurationMid: '0.24s',
  motionDurationSlow: '0.32s',
  motionEaseInOut: 'cubic-bezier(0.16, 1, 0.3, 1)',
  boxShadow: '0 1px 2px rgba(15, 23, 42, 0.04), 0 10px 30px rgba(15, 23, 42, 0.06)',
}

export const lightTheme = {
  algorithm: defaultAlgorithm,
  token: tokens,
  components: {
    Layout: {
      bodyBg: '#F5F7FB',
      headerBg: 'rgba(255, 255, 255, 0.78)',
      siderBg: '#FFFFFF',
    },
    Button: {
      fontWeight: 600,
      controlHeight: 40,
      borderRadius: 10,
      primaryShadow: 'none',
    },
    Menu: {
      itemBg: 'transparent',
      itemHoverBg: 'rgba(15, 23, 42, 0.04)',
      itemSelectedBg: 'rgba(47, 107, 255, 0.1)',
      itemSelectedColor: '#1D4ED8',
      itemBorderRadius: 10,
      itemHeight: 44,
      iconSize: 18,
    },
    Card: {
      borderRadiusLG: 18,
      borderRadiusSM: 14,
      colorBorderSecondary: '#E4E7EC',
      bodyPadding: 24,
      headerPadding: 24,
    },
    Table: {
      headerBg: '#F8FAFC',
      headerColor: '#0F172A',
      rowHoverBg: '#F8FAFC',
      borderColor: '#E5E7EB',
      cellPaddingBlock: 14,
      cellPaddingInline: 16,
    },
    Input: {
      borderRadius: 12,
      colorBorder: '#D8E0EA',
      hoverBorderColor: '#BFD0FF',
      activeBorderColor: '#2F6BFF',
      activeShadow: '0 0 0 3px rgba(47, 107, 255, 0.12)',
    },
    Select: {
      borderRadius: 12,
      colorBorder: '#D8E0EA',
      hoverBorderColor: '#BFD0FF',
      activeBorderColor: '#2F6BFF',
      activeShadow: '0 0 0 3px rgba(47, 107, 255, 0.12)',
      optionPadding: '8px 12px',
    },
    DatePicker: {
      borderRadius: 12,
      colorBorder: '#D8E0EA',
      hoverBorderColor: '#BFD0FF',
      activeBorderColor: '#2F6BFF',
      activeShadow: '0 0 0 3px rgba(47, 107, 255, 0.12)',
    },
    Modal: {
      borderRadiusLG: 20,
      titleFontSize: 18,
      titleLineHeight: 1.2,
      contentBg: '#FFFFFF',
      headerBg: '#FFFFFF',
      footerBg: '#FFFFFF',
    },
    Drawer: {
      borderRadiusLG: 20,
      footerPaddingBlock: 20,
      footerPaddingInline: 24,
      bodyPadding: 24,
      headerPadding: 24,
    },
    Form: {
      labelFontSize: 12,
      labelColor: '#475467',
      verticalLabelPadding: '0 0 8px',
      itemMarginBottom: 20,
    },
    Segmented: {
      itemSelectedBg: '#FFFFFF',
      trackBg: '#EDF2FF',
      itemColor: '#475467',
      itemSelectedColor: '#0F172A',
    },
    Tag: {
      borderRadiusSM: 999,
      defaultBg: 'rgba(47, 107, 255, 0.08)',
      defaultColor: '#1D4ED8',
      borderColor: 'transparent',
    },
    Empty: {
      colorTextDescription: '#667085',
    },
  },
}
